[theme]
base="light"
primaryColor="#0077b6"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f1f3f6"
textColor="#000000"
font="sans serif"

[server]
headless = true

[client]
showSidebarNavigation = false
